# Generated by Django 5.2 on 2025-05-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0005_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
    ]
