# Generated by Django 5.2 on 2025-05-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reservation_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation_date', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation_time', models.TextField(blank=True, max_length=1000, null=True)),
                ('reservation_guests', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
